import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import './globals.css'
import {NavBar} from "@/components/NavBar";
import {Separator} from "@/components/ui/separator";
import {ThemeProvider} from "@/providers/ThemeProvider";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <ClerkProvider>
    <html lang="en">
      <ThemeProvider>
        <body className={inter.className}>
        <div className="flex min-h-screen w-full flex-col items-center dark:bg-black">
          <NavBar />
          <Separator />
          <main className="flex flex-grow w-full justify-center items-center dark:bg-neutral-950">
            {children}
          </main>
        </div>
      </body>
      </ThemeProvider>

    </html>
      </ClerkProvider>
  )
}
